lifelong_therapy/appointment/urls.py
from django.urls import path

from . import views

app_name = "appointment"

urlpatterns = [
    path("", views.index, name="index"),
    path("appointment_schedule_times/", views.appointment_schedule_times, name="appointment schedule times")
]

lifelong_therapy/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>", views.detail, name="detail")
]

lifelong_therapy/lifelong_therapy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from . import views

urlpatterns = [
    path("lang/<slug:lang>",views.language_picker, name="language-picker"),
    path("popup-form/", views.popup_form, name="popup-form"),
    path("", views.home, name="home"),
    path("online-therapy/", views.online_therapy, name="online-therapy"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("services/<slug:name>", views.services, name="services"),
    path("blog/", include("blog.urls")),
    path("book-appointment/", include("appointment.urls")),
    path('master/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lifelong_therapy/appointment/models.py
import datetime
import pytz

from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone

class Therapist(models.Model):
    therapist_name = models.CharField(max_length = 40)
    therapist_email = models.EmailField(default="unspecified@foo.com", max_length = 40)

    def __str__(self):
        return self.therapist_name

class Patient(models.Model):
    patient_name = models.CharField(max_length = 40)
    patient_email = models.EmailField(default="unspecified@foo.com", max_length = 40)
    patient_phone_number = models.CharField(max_length = 10, blank = True) 
    # TODO consider using regex in future for only UK numbers
    # TODO consider adding text message to the patients phone in UK 
    '''in UK numbers are formatted like this;
    +44 7911 123456 global
    0 7911 123456 local
    '''
    # tzinfo=pytz.timezone("Europe/London")
    # p = Patient(patient_name="patient pelia", patient_phone_number="404",appointment_date=datetime.datetime(2020,1,1,15,0,0,tzinfo=pytz.UTC), therapist=t) 
    appointment_date = models.DateTimeField("date appointed")
    therapist = models.ForeignKey(Therapist, on_delete=models.CASCADE)

    def __str__(self):
        return self.patient_name

    def is_appointment_date_near(self):
        return self.appointment_date <= timezone.now() + datetime.timedelta(days = 3)

lifelong_therapy/appointment/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import datetime
import pytz
from .models import Therapist, Patient

# Get therapists and display them
def index(request):
    if request.method == "POST":
        fullname = request.POST.get("fullname")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        date = request.POST.get("date")
        time = request.POST.get("time")

        year, month, day = date.split("-")
        year, month, day = int(year), int(month), int(day)
        hour, minute = time.split(":")
        hour, minute = int(hour), int(minute)

        # SEND EMAIL HERE
        import os
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
        message = Mail(
            from_email='domain@lifelongtherapy.com',
            to_emails='info@lifelongtherapy.com',
            subject='A new person has scheduled an appointment!',
            html_content=('<strong>{} scheduled an appointment at {}, {}. For further details like email and phone number please check the panel.</strong>').format(fullname, time, date))
        try:
            sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
            response = sg.send(message)
            print(response.status_code)
            print(response.body)
            print(response.headers)
        except Exception as e:
            print(e.message)
        #####

        patient = Patient()
        patient.patient_name = fullname
        patient.patient_email = email
        patient.patient_phone_number = phone
        patient.appointment_date = datetime.datetime(year,month,day,hour,minute,0,tzinfo=pytz.utc)
        patient.therapist = Therapist.objects.all()[0]
        patient.save()

    #therapists_list = Therapist.objects.all
    #context = {"therapists_list": therapists_list}
    request.session.setdefault("lang", "en")
    lang = request.session["lang"]
    if lang == "tr":
        parentBase = "base_tr.html"
        context = {"lang":lang, "parentBase": parentBase}
    else:
        parentBase = "base.html"
        context = {"lang":lang, "parentBase": parentBase}
        
    return render(request, "appointment/index.html", context)

def appointment_schedule_times(request):
    if request.method == 'GET':
        times_list = []
        selected_date = request.GET["date"]
        year,month,day = selected_date.split("-")
        year, month, day = int(year), int(month), int(day)
        example_therapist = Therapist.objects.all()[:1].get() # Later on therapist names can be selected by user or it will be in administritive order
        patients_on_date = example_therapist.patient_set.all().filter(appointment_date__date=(datetime.date(year,month,day)))
        therapist_time_schedule = [datetime.datetime(year,month,day,i,0,0,tzinfo=pytz.utc) for i in range(9,17)]

        for p in patients_on_date:
            if p.appointment_date in therapist_time_schedule:
                therapist_time_schedule.remove(p.appointment_date)

        for t in therapist_time_schedule:
            times_list.append("{0}:{1}0".format(t.hour,t.minute))
            
        return JsonResponse({
            "schedule_times": times_list
        })
    else:
        return HttpResponse("API doesn't work that way")

lifelong_therapy/templates/components/appointmentForm.html
<!-- MultiStep Form -->
<div class="container dark-blue-background" >
    <div class="row justify-content-md-center" style="margin-top: -2rem; min-height: 600px; padding-top: 2rem; ">
        <div class="col col-md-12" >
            <form id="msform" method="POST" action=".">
                {% csrf_token %}
                <!-- progressbar -->
                <ul id="progressbar">
                    
                    {% if lang == "tr" %}
                        <li class="active"> Kişisel Detaylar</li>
                        <li>Randevu Tarih</li>
                        <li>Randevu Zaman</li>
                    {% else %}
                        <li class="active">Personal Details</li>
                        <li>Appointment Date</li>
                        <li>Appointment Time</li>
                    {% endif %}
                </ul>
                <!-- fieldsets -->
                <fieldset>
                    
                    {% if lang == "tr" %}
                        <h2 class="fs-title">Kişisel Detaylar</h2>
                        <!--<h3 class="fs-subtitle">Tell us something more about you</h3>-->
                        <input type="text" name="fullname" placeholder="Ad Soyad"/>
                        <input type="text" name="email" placeholder="Email"/>
                        <input type="text" name="phone" placeholder="Telefon"/>
                        
                        <input type="button" name="next" class="next action-button" value="İlerle"/>
                    {% else %}
                        <h2 class="fs-title">Personal Details</h2>
                        <!--<h3 class="fs-subtitle">Tell us something more about you</h3>-->
                        <input type="text" name="fullname" placeholder="Full Name"/>
                        <input type="text" name="email" placeholder="Email"/>
                        <input type="text" name="phone" placeholder="Phone"/>
                        
                        <input type="button" name="next" class="next action-button" value="Next"/>    
                    {% endif %}    
                    
                </fieldset>
                <fieldset>
                    
                    {% if lang == "tr" %}
                        <h2 class="fs-title">Randevu Tarih</h2>
                        <!--<h3 class="fs-subtitle">Your presence on the social network</h3>--> 
                    
                        <p><i class="fas fa-clock"></i> 50 dakika</p>
                        <p><i class="fas fa-user"></i> 1 kişi</p>
                        <p style="padding-bottom: 20px;"><i class="fas fa-map-marker-alt"></i> LifeLong London, UK </p>
                        <input type="text" id="datepicker" name="date" placeholder="Tarih">

                        <input type="button" name="previous" class="previous action-button-previous" value="Geri"/>
                        <input type="button" name="next" class="next action-button get-time-button" value="İlerle"/>
                    {% else %}
                        <h2 class="fs-title">Appointment Date</h2>
                        <!--<h3 class="fs-subtitle">Your presence on the social network</h3>--> 
                    
                        <p><i class="fas fa-clock"></i> 50 mins</p>
                        <p><i class="fas fa-user"></i> 1 person</p>
                        <p style="padding-bottom: 20px;"><i class="fas fa-map-marker-alt"></i> LifeLong London, UK </p>
                        <input type="text" id="datepicker" name="date" placeholder="Date">

                        <input type="button" name="previous" class="previous action-button-previous" value="Previous"/>
                        <input type="button" name="next" class="next action-button get-time-button" value="Next"/>
                    {% endif %}
        
                </fieldset>
                <fieldset>
                    
                    {% if lang == "tr" %}
                        <h2 class="fs-title">Randevu Zaman</h2>
                        <!--<h3 class="fs-subtitle">Fill in your credentials</h3>-->
                    {% else %}
                        <h2 class="fs-title">Appointment Time</h2>
                        <!--<h3 class="fs-subtitle">Fill in your credentials</h3>-->
                    {% endif %}

                    <!-- Group of default radios - option 1 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample1" name="time">
                        <label class="custom-control-label" for="defaultGroupExample1">null</label>
                    </div>
    
                    <!-- Group of default radios - option 2 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample2" name="time">
                        <label class="custom-control-label" for="defaultGroupExample2">null</label>
                    </div>
    
                    <!-- Group of default radios - option 3 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample3" name="time">
                        <label class="custom-control-label" for="defaultGroupExample3">null</label>
                    </div>

                    <!-- Group of default radios - option 4 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample4" name="time">
                        <label class="custom-control-label" for="defaultGroupExample4">null</label>
                    </div>

                    <!-- Group of default radios - option 5 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample5" name="time">
                        <label class="custom-control-label" for="defaultGroupExample5">null</label>
                    </div>

                    <!-- Group of default radios - option 6 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample6" name="time">
                        <label class="custom-control-label" for="defaultGroupExample6">null</label>
                    </div>

                    <!-- Group of default radios - option 7 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample7" name="time">
                        <label class="custom-control-label" for="defaultGroupExample7">null</label>
                    </div>

                    <!-- Group of default radios - option 8 -->
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultGroupExample8" name="time">
                        <label class="custom-control-label" for="defaultGroupExample8">null</label>
                    </div>

                    <input type="button" name="previous" class="previous action-button-previous" value="Previous"/>
                    <input type="submit" name="submit" class="submit action-button" value="Submit"/>
                </fieldset>
            </form>
        </div>
    </div>
</div>
<!-- /.MultiStep Form -->

lifelong_therapy/templates/components/articleCards.html
<div class="container mt-5">
  
  {% if lang == "tr" %}
    <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">Blog</h6>
    <h3 class="font-weight-bold text-center pb-2">Bizden Son Makaleleri Oku</h3>  
  {% else %}
    <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">Blog</h6>
    <h3 class="font-weight-bold text-center pb-2">Read Latest Articles From Us</h3>
  {% endif %}
  <hr class="w-header my-4">
  <p class="lead text-center text-muted pt-2 mb-5"></p>

  <div class="row">
    {% if latest_article_list %}
      {% for article in latest_article_list %}
        <div class="col-lg-4 col-md-12 mb-lg-0 mb-4 d-flex align-items-stretch">
          <!-- Card -->
          <div class="card hoverable">
            <img class="card-img-top" src="{{article.post_image.url}}" alt="Card image cap">
            <!-- Card content -->
            <div class="card-body">
              
              {% if lang == "tr" %}
                <a href="{% url "blog:detail" article.id %}" class="black-text" style="font-weight: bold;">{{article.post_headerTR}}</a>
                <p class="card-title text-muted font-small mt-3 mb-2">{{article.post_contentTR|safe|slice:":100"}}...</p>
                <a href="{% url "blog:detail" article.id %}" type="button" class="custom-button">Daha fazla oku<i class="fa fa-angle-right ml-2"></i></a>
              {% else %}
                <a href="{% url "blog:detail" article.id %}" class="black-text" style="font-weight: bold;">{{article.post_header}}</a>
                <p class="card-title text-muted font-small mt-3 mb-2">{{article.post_content|safe|slice:":100"}}...</p>
                <a href="{% url "blog:detail" article.id %}" type="button" class="custom-button">Read more<i class="fa fa-angle-right ml-2"></i></a>
              {% endif %}
                
              
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}

  </div>

  <div class="text-center mt-5 mb-5">
    
    {% if lang == "tr" %}
      <a class="btn btn-lg custom-button" href="{% url "blog:index" %}">MAKALELERE GÖZAT</a>
    {% else %}
      <a class="btn btn-lg custom-button" href="{% url "blog:index" %}">BROWSE ARTICLES</a>  
    {% endif %}
  </div>

</div>

lifelong_therapy/templates/components/banner.html
<div class="banner">
    <div class="banner_img-wrapper">
      <img class="banner_img" src="/static/banner.png" alt="banner background">
    </div>
    <div class="banner_text">
      
      {% if lang == "tr" %}
        <h3 class="banner-header"><i class="fas fa-calendar-day"></i> Ücretsiz Online Randevu</h3>
        <p class="banner-subheader"> 30 dakikalık ücretsiz danışmanlık hizmeti için formu doldurun </p>
        <a href="https://forms.gle/6VnAwZCqbwWc3tCx7" class="btn btn-white btn-shadow"><i class="fas fa-caret-right"></i> Başla</a>
      {% else %}
        <h3 class="banner-header"><i class="fas fa-calendar-day"></i> Free Online Appointment</h3>
        <p class="banner-subheader">Fill out the form to arrange free 30 minutes consulting </p>
        <a href="https://forms.gle/6VnAwZCqbwWc3tCx7" class="btn btn-white btn-shadow"><i class="fas fa-caret-right"></i> Begin</a>
      {% endif %}
    </div>
    <svg class="curve-mask" preserveAspectRatio="none" viewBox="0 0 1024 96" xmlns="http://www.w3.org/2000/svg">
      <g id="Curve-Experiments" fill="none" fill-rule="evenodd">
        <g id="Curve-A" transform="translate(0 -349)" fill="#FFF" fill-rule="nonzero">
          <path d="M0 398.663c470.834 145.75 491.222-163.652 1024 0v46.08H0v-46.08z" id="mo-curve"/>
        </g>
      </g>
    </svg> 
</div>

lifelong_therapy/templates/components/card.html
<div class="card">
    <!-- Card image -->
    <img class="card-img-top" src={{cardImage}} alt="Card image cap">
    <!-- Card content -->
    <div class="card-body text-center">
        <!-- Title -->
        <h4 class="card-title py-2"><a>{{cardTitle}}</a></h4>
        <!-- Text -->
        <p class="card-text mb-3">{{cardText}}</p>
        <!-- Button -->
        <a type="button" href="{% url 'services' slug %}" class="btn purple-gradient btn-rounded"><i class="fas fa-caret-right mr-2" aria-hidden="true"></i>Details</a>
    </div>

</div>

lifelong_therapy/templates/components/contact.html
<div class="z-depth-1 px-5 py-1 text-center" style="background-image: url('/static/contact.jpg'); background-size: cover; background-position: center center;">
    
    {% if lang == "tr" %}
        <h3 class="text-center font-weight-bold text-white mt-5 mb-3">Bize Ulaşın</h3>
        <h4 class="text-center font-weight-normal text-white mx-auto mb-4 pb-2">Sizden haber almayı bekliyoruz!</h4>
    {% else %}
        <h3 class="text-center font-weight-bold text-white mt-5 mb-3">Contact Us</h3>
        <h4 class="text-center font-weight-normal text-white mx-auto mb-4 pb-2">We love to hear from you!</h4>
    {% endif %}

    <form class="mb-5 mx-md-5" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 mb-4">
                {% if lang == "tr" %}
                    <input type="text" id="name" name="name" class="form-control" placeholder="İsim">
                {% else %}
                    <input type="text" id="name" name="name" class="form-control" placeholder="Name">
                {% endif %}
            </div>
            <div class="col-md-4 mb-4">
                <input type="email" id="email" name="email" class="form-control" placeholder="Email">
            </div>
            <div class="col-md-4 mb-4">
                {% if lang == "tr" %}
                    <input type="number" id="phone" name="phone" class="form-control" placeholder="Telefon No">
                {% else %}
                    <input type="number" id="phone" name="phone" class="form-control" placeholder="Phone Number">
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 mb-4">
                {% if lang == "tr" %}
                    <input type="text" id="subject" name="subject" class="form-control" placeholder="Konu">
                {% else %}
                    <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject">
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group mb-4">
                    {% if lang == "tr" %}
                        <textarea class="form-control rounded" id="message" name="message" rows="3" placeholder="Nasıl yardımcı olabiliriz?"></textarea>
                    {% else %}
                        <textarea class="form-control rounded" id="message" name="message" rows="3" placeholder="How can we help?"></textarea>
                    {% endif %}
                </div>
                <div class="text-center">
                    {% if lang == "tr" %}
                        <button type="submit" class="btn btn-elegant" style="background-color:#0094d9 !important;">Gönder</button>
                    {% else %}
                        <button type="submit" class="btn btn-elegant" style="background-color:#0094d9 !important;">Send</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
</div>

  
  

lifelong_therapy/templates/components/counter.html
<div class="white-text p-5 rounded dark-blue-background">
    <div class="row">

        <div class="col-md-4 mb-4">
            <div class="row">
                <div class="col-6 pr-0">
                    <h4 class="display-4 text-right mb-0 counter-location" data-from="0" data-to="2" data-time="2000">2</h4>
                </div>

                <div class="col-6">
                    
                    {% if lang == "tr"  %}
                        <p class="text-uppercase font-weight-normal mb-1">Konumlar</p>
                    {% else %}
                        <p class="text-uppercase font-weight-normal mb-1">Locations</p>
                    {% endif %}
                    <p class="mb-0"><i class="fas fa-map-marked-alt fa-2x mb-0"></i></p>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-4">
            <div class="row">
                <div class="col-6 pr-0">
                    <h4 class="display-4 text-right mb-0 counter-patient" data-from="0" data-to="800" data-time="2000">800</h4>
                </div>

                <div class="col-6">

                    {% if lang == "tr" %}
                        <p class="text-uppercase font-weight-normal mb-1">Hastalar</p>
                    {% else %}
                        <p class="text-uppercase font-weight-normal mb-1">Patients</p>
                    {% endif %}
                    <p class="mb-0"><i class="fas fa-users fa-2x mb-0"></i></p>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-4">
            <div class="row">
                <div class="col-6 pr-0">
                    <h4 class="display-4 text-right"><span class="d-flex justify-content-end"><span class="counter-satisfaction" data-from="0" data-to="99" data-time="2000">99</span> %</span></h4>
                </div>

                <div class="col-6">

                    {% if lang == "tr" %}
                        <p class="text-uppercase font-weight-normal mb-1">Memnuniyet</p>
                    {% else %}    
                        <p class="text-uppercase font-weight-normal mb-1">Satisfaction</p>
                    {% endif %}
                    <p class="mb-0"><i class="fas fa-smile fa-2x mb-0"></i></p>
                </div>
            </div>
        </div>

    </div>
</div>
  

lifelong_therapy/templates/components/floatingButton.html
<a href="{% url 'contact' %}" class="floating-button">
    <i class="fas fa-phone my-floating-button-offset"></i>
</a>

lifelong_therapy/templates/components/navbar.html
{% load static %}

<nav class="mb-1 navbar fixed-top navbar-expand-lg navbar-light default-color custom-navbar">
    <div class="container" style="max-width: 1200px;">
        <a class="navbar-brand" href="/">
            <img src="{% static "logo.png" %}" alt="lifelong counselling logo" width="200px">
        </a>
        <button class="navbar-toggler blue-gradient-background" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
            aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown custom-item">
                    {% if lang == "tr" %}
                        <a class="nav-link dropdown-toggle custom-link" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Servisler
                        </a>
                        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="addiction-counselling" %}">Bağımlılık Danışmanlığı</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="adolescent-counselling" %}">Ergen Danışmanlığı</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="couples-and-marriage-counselling" %}">Çift ve Evlilik Danışmanlığı</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="family-counselling" %}">Aile Danışmanlığı</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="individual-counselling" %}">Bireysel Danışmanlık</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="children-counselling" %}">Çocuk Danışmanlığı</a>                       
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle custom-link" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Services
                        </a>
                        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="addiction-counselling" %}">Addiction Counselling</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="adolescent-counselling" %}">Adolescent Counselling</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="couples-and-marriage-counselling" %}">Couples and Marriage Counselling</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="family-counselling" %}">Family Counselling</a>
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="individual-counselling" %}">Individual Counselling</a>  
                            <a class="dropdown-item" style="color: #0094d9;font-family: 'Abril-Fatface', serif;" href="{% url 'services' name="children-counselling" %}">Children Counselling</a>                    
                        </div>
                    {% endif %}
                </li>
                <li class="nav-item custom-item">
                    <a class="nav-link custom-link" href="{% url 'blog:index' %}">Blog</a>
                </li>
                <li class="nav-item custom-item">
                    
                    {% if lang == "tr" %}
                        <a class="nav-link custom-link" href="{% url 'about' %}">Hakkında</a>
                    {% else %}
                        <a class="nav-link custom-link" href="{% url 'about' %}">About</a>
                    {% endif %}
                </li>
                <li class="nav-item custom-item">
                    
                    {% if lang == "tr" %}
                        <a class="nav-link custom-link" href="{% url 'contact' %}">İletişim</a>
                    {% else %}
                        <a class="nav-link custom-link" href="{% url 'contact' %}">Contact</a>
                    {% endif %}
                </li>
                <li class="nav-item custom-item">

                    {% if lang == "tr" %}
                        <a class="nav-link custom-link" href="{% url 'online-therapy' %}">Online Terapi</a>
                    {% else %}
                        <a class="nav-link custom-link" href="{% url 'online-therapy' %}">Online Therapy</a>
                    {% endif %}
                </li>
                <li class="nav-item">

                    {% if lang == "tr" %}
                        <a class="nav-link custom-button" href="{% url 'appointment:index' %}"><i class="fas fa-calendar-alt"></i> Randevu</a>
                    {% else %}
                        <a class="nav-link custom-button" href="{% url 'appointment:index' %}"><i class="fas fa-calendar-alt"></i> Appointment</a>
                    {% endif %}
                </li>
            </ul>
            <ul class="navbar-nav ml-auto nav-flex-icons social-links">
                <li class="nav-item">
                    <a href="https://www.facebook.com/lifelongw/" target=”_blank” class="nav-link waves-effect waves-light" style="margin-top: 10px;">
                        <i class="fab fa-facebook" style="color: #0d47a1;"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://twitter.com/lifelongtherapy" target=”_blank” class="nav-link waves-effect waves-light" style="margin-top: 10px;">
                        <i class="fab fa-twitter" style="color: #4285F4;"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://www.instagram.com/lifelongtherapy/" target=”_blank” class="nav-link waves-effect waves-light" style="margin-top: 10px;">
                        <i class="fab fa-instagram" style="color: #DD2A7B"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="https://wa.me/447392206299" target=”_blank” class="nav-link waves-effect waves-light" style="margin-top: 10px;">
                        <i class="fab fa-whatsapp" style="color: #25D366"></i>
                    </a>
                </li>

                <li class="nav-item ml-4">
                    <a href="{% url 'language-picker' "tr" %}" style="margin-top: 10px;">
                        <img src="{% static "tr.png" %}" height="40px" />
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'language-picker' "en" %}" style="margin-top: 10px;">
                        <img src="{% static "uk.png" %}" height="40px" />
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>